### ISSUE TITLE
BLOB types are registered as VARCHAR

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#82]
GSC is getting blob columns as strings, check blob_content column:

```
scala> spark.sql("describe table files").show()
+---------------+---------+-------+
|       col_name|data_type|comment|
+---------------+---------+-------+
|  repository_id|   string|   null|
|      file_path|   string|   null|
|      blob_hash|   string|   null|
|      tree_hash|   string|   null|
|tree_entry_mode|   string|   null|
|   blob_content|   string|   null|
|      blob_size|   bigint|   null|
+---------------+---------+-------+

```

**Comment by dpordomingo** [comment]
just pinging myself to review again https://github.com/src-d/gitbase-spark-connector/issues/81 once this is merged :dancer:

**Comment by ajnavarro** [comment]
It is resolved in https://github.com/src-d/go-mysql-server/pull/637

**Comment by ajnavarro** [comment]
Close it when we update the gitbase version GSC is using

**Comment by erizocosmico** [comment]
Should we wait until 0.20 or can we update it to one of the recent betas?

**Comment by ajnavarro** [comment]
:+1: to update to recent betas

**Comment by erizocosmico** [comment]
Tried with a gitbase that already has https://github.com/src-d/go-mysql-server/pull/637 locally and the most recent beta docker image. It still fails on both of them.

Did you test gitbase-spark-connector issue was gone with src-d/go-mysql-server#637? Because maybe we reintroduced it or something.

**Comment by ajnavarro** [comment]
@erizocosmico Yep, I changed manually https://github.com/src-d/go-mysql-server/pull/637 before making the PR and tested it... I did more tests, like change JDBC driver to mysql one.

**Comment by erizocosmico** [comment]
![Screenshot 2019-04-11 at 17 06 14](https://user-images.githubusercontent.com/1312023/55968404-349e4b00-5c7c-11e9-93d3-447a2a531449.png)

AFAIK #637 is included in v0.20.x betas

**Comment by erizocosmico** [comment]
Blocked until https://github.com/src-d/go-mysql-server/pull/673 is on gitbase and a version with it has been released.

**Comment by erizocosmico** [comment]
Fix included in https://github.com/src-d/gitbase/pull/795
